name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Practice
      working-directory: ./sols/practice
      run: cargo build --verbose

    - uses: actions/checkout@v4
    - name: Build HW1
      working-directory: ./sols/hw1
      run: cargo build --verbose

    - uses: actions/checkout@v4
    - name: Build HW2
      working-directory: ./sols/hw2
      run: cargo build --verbose

    - uses: actions/checkout@v4
    - name: Build HW3
      working-directory: ./sols/hw3
      run: cargo build --verbose

    - uses: actions/checkout@v4
    - name: Build HW4
      working-directory: ./sols/hw4
      run: cargo build --verbose
