name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Practice
      working-directory: ./solutions/rust/practice
      run: cargo build --verbose

    - uses: actions/checkout@v4
    - name: Build HW1
      working-directory: ./solutions/rust/hw1
      run: cargo build --verbose
